name: chopar_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.17+17

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  modal_bottom_sheet: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  #  flutter_stories: ^0.3.0
  flutter_bloc: ^7.3.0
  intl_phone_number_input: ^0.7.0+2
  niku: ^1.1.3
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2
  intl: ^0.17.0
  equatable: ^2.0.3
  collection: ^1.15.0
  flutter_svg: ^0.22.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  uuid: ^3.0.4
  meta: ^1.3.0
  hashids2: ^2.0.0
  direct_select: ^2.0.0
  scrollable_list_tabview: 0.2.0-nullsafety
  flutter_slidable: ^0.6.0
  timer_count_down: ^2.2.0
  flutter_hooks: ^0.18.0
  group_list_view: ^1.1.1
  overlay_dialog: ^0.2.1
  flutter_staggered_animations: ^1.0.0
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  geolocator: ^7.7.0
  flutter_form_builder: 7.0.0-beta.0
  form_builder_validators: ^7.1.0
  form_builder_phone_field: 1.0.0-beta.0
  dart_date: ^1.1.0
  flutter_html: ^2.1.5
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  extended_tabs: ^2.3.0
  yandex_mapkit: ^1.1.1
  font_awesome_flutter: ^9.1.0
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.12
  flutter_datetime_picker: ^1.5.1
  pin_code_fields: ^7.3.0
  flutter_platform_widgets: ^1.11.1
  firebase_messaging: ^11.0.0
  firebase_core: ^1.10.5
  awesome_notifications: ^0.6.19
  location: ^4.3.0
  fluttertoast: ^8.0.8
  flash: ^2.0.3+1
  top_snackbar_flutter: ^1.0.2
  another_flushbar: ^1.10.28
  connectivity_plus: ^2.2.1
  html: ^0.15.0
  simple_html_css: ^3.0.1+1
  upgrader: ^3.13.0
  scrollable_positioned_list: ^0.2.3
  flutter_rating_bar: ^4.0.0
  scrolls_to_top: ^1.1.1

dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1
  build_runner:
  mobx_codegen:
  hive_generator: ^1.1.1

flutter_native_splash:
  background_image: "assets/images/launch.png"
  ios: true
  android: true
  android_gravity: center
  ios_content_mode: center

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Italic.ttf
          style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages